<?php

namespace zaboy\test\async\Promise\Factory\Middleware;

use zaboy\async\Promise\Factory\Adapter\MySqlAdapterFactory;
use zaboy\async\Promise\Factory\BrokerFactory;
use Interop\Container\ContainerInterface;
use zaboy\rest\TableGateway\TableManagerMysql;
use zaboy\async\Promise\Middleware\CrudPromise;
use zaboy\async\Promise\Factory\Middleware\CrudPromiseFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class CrudPromiseFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BrokerFactory
     */
    protected $object;

    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = include './config/container.php';
        $this->object = $this->container->get(CrudPromiseFactory::KEY_MIDDLEWARE_CRUD_PROMISE);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testMySqlAdapterFactory__makePromise()
    {
        $this->assertInstanceOf(
                'zaboy\async\Promise\Middleware\CrudPromise', $this->object
        );
    }

}
