<?php

namespace zaboy\test\async\Queue\Factory\DataStore;

use Interop\Container\ContainerInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class ClientDataStoreAbstractFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Returner
     */
    protected $object;

    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = include './config/container.php';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testClientAbstractFactory__invoke()
    {
        $this->object = $this->container->get('test_ClientDataStore');
        $this->assertSame(
                get_class($returnedResponse = $this->object), 'zaboy\async\Queue\DataStore\ClientDataStore'
        );
    }

}
