<?php

namespace zaboy\test\async\Promise\Factory\Middleware;

use zaboy\async\Promise\Factory\Adapter\MySqlAdapterFactory;
use zaboy\async\Promise\Factory\Broker\PromiseBrokerFactory;
use Interop\Container\ContainerInterface;
use zaboy\rest\TableGateway\TableManagerMysql;
use zaboy\async\Promise\Middleware\CrudPromise;
use zaboy\async\Promise\Factory\Middleware\CrudPromiseFactory;
use zaboy\rest\DataStore\HttpClient;
use zaboy\async\Promise\PromiseClient;
use zaboy\async\Promise\Adapter\MySqlPromiseAdapter;
use Zend\Http\Client;
use Zend\Http\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class CrudPromiseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \zaboy\rest\DataStore\HttpClient
     */
    protected $object;

    /**
     * @var MySqlPromiseAdapter
     */
    protected $adapter;

    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = include './config/container.php';
        $this->object = $this->container->get('test_rest_middleware_datastore');
        $this->adapter = $this->container->get(MySqlAdapterFactory::KEY_PROMISE_ADAPTER);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function test__createPromise()
    {

        $promiseData = $this->object->create([]);
        $promise = new PromiseClient($this->adapter, $promiseData[MySqlPromiseAdapter::PROMISE_ID]);
        $this->assertInstanceOf(
                'zaboy\async\Promise\PromiseClient', $promise
        );
        $this->assertEquals(
            PromiseClient::PENDING, $promise->getState()
        );
    }


    public function test_resolvePromise()
    {
        $promiseData = $this->object->create([]);
        $promiseData[MySqlPromiseAdapter::STATE] = PromiseClient::FULFILLED;
        $promiseData[MySqlPromiseAdapter::RESULT] = 'test_result_success_fulfill';

        $this->object->update($promiseData);

        $promise = new PromiseClient($this->adapter, $promiseData[MySqlPromiseAdapter::PROMISE_ID]);
        $result = $promise->wait(false);
        $this->assertEquals(
            'test_result_success_fulfill', $result
        );
        $this->assertEquals(
            PromiseClient::FULFILLED, $promise->getState()
        );
    }


    public function test_rejectPromise()
    {
        $promiseData = $this->object->create([]);
        $promiseData[MySqlPromiseAdapter::STATE] = PromiseClient::REJECTED;
        $promiseData[MySqlPromiseAdapter::RESULT] = 'test_result_error_reject';

        $this->object->update($promiseData);

        $promise = new PromiseClient($this->adapter, $promiseData[MySqlPromiseAdapter::PROMISE_ID]);
        $result = $promise->wait(false);
        $this->assertInstanceOf(
            'zaboy\async\Promise\Determined\Exception\RejectedException', $result
        );
        $this->assertEquals(
            PromiseClient::REJECTED, $promise->getState()
        );
    }


    public function test_tryToChangeFulfilledPromise()
    {
        $promiseData = $this->object->create([]);
        $promiseData[MySqlPromiseAdapter::STATE] = PromiseClient::FULFILLED;
        $promiseData[MySqlPromiseAdapter::RESULT] = 'test_result_success_fulfill';
        $this->object->update($promiseData);

        $promise = new PromiseClient($this->adapter, $promiseData[MySqlPromiseAdapter::PROMISE_ID]);
        $result = $promise->wait(false);
        $this->assertEquals(
            'test_result_success_fulfill', $result
        );
        $this->assertEquals(
            PromiseClient::FULFILLED, $promise->getState()
        );

        $promiseData[MySqlPromiseAdapter::STATE] = PromiseClient::REJECTED;
        $this->setExpectedExceptionRegExp('\zaboy\rest\DataStore\DataStoreException');
        $this->object->update($promiseData);
    }
}
