<?php

namespace zaboy\test\async\Message\Factory;

use zaboy\test\async\StoreFactoryAbstract;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class StoreFactoryTest extends StoreFactoryAbstract
{

    const FACTORY_CLASS = 'zaboy\async\Message\Factory\StoreFactory';
    const STORE_CLASS = 'zaboy\async\Message\Store';

}
