<?php

namespace zaboy\test\async\Queue\Factory\Adapter;

use zaboy\async\Queue\Factory\Adapter\MemoryStoresAdapterFactory;
use zaboy\rest\TableGateway\TableManagerMysql;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class DataStoresAdapterFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Returner
     */
    protected $object;

    /**
     * @var Zend\Db\Adapter\Adapter
     */
    protected $adapter;

    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = include './config/container.php';
        $this->object = $this->container->get('TestDataStoresOueueAdapter');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testMySqlAdapterFactory__invoke()
    {
        $this->assertTrue(
                is_a($this->object, 'zaboy\async\Queue\Adapter\DataStores', true)
        );
    }

}
